config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :brands
    get 'home/index' 
    root 'home#index' 
  devise_for :users
  resources :upload_logos
  resources :add_texts
  resources :custom_military_hats
  resources :custom_golf_hats
  resources :custom_athletic_hats
  resources :custom_bucket_hats
  resources :custom_trucker_hats
  resources :custom_panel_hats
  resources :custom_beanies
  resources :custom_camo_hats
  resources :custom_strapback_hats
  resources :custom_fitted_hats
  resources :custom_snapbacks
  get 'home/custom_snapbacks'
  get 'home/custom_fitted_hats'
  get 'home/custom_dad_hats'
  get 'home/custom_camo_hats'
  get 'home/login_form'
  get 'home/forget_psw'
  get 'home/signup_form'
  get 'home/checkout'
  get 'home/checkout_shipping'
  get 'home/checkout_payment'
  get 'home/contact'
  post 'home/contact_us_mailer'
  resources :shippings
  resources :addresses
  resources :order_statuses
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  resources :orders
	resources :charges
  resources :faqs
end

app/models/custom_bucket_hat.rb
class CustomBucketHat < ApplicationRecord
	mount_uploader :image, ImageUploader
	mount_uploader :back_image, BackImageUploader
	mount_uploader :left_image, LeftImageUploader
	mount_uploader :right_image, RightImageUploader
	mount_uploader :logo, LogoUploader
	belongs_to :order, optional: true
	has_many :order_items
	belongs_to :brand
end

app/controllers/custom_bucket_hats_controller.rb
class CustomBucketHatsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_custom_bucket_hat, only: [:show, :edit, :update, :destroy]

  # GET /custom_bucket_hats
  # GET /custom_bucket_hats.json
  def index
    if params[:brand].blank?
      @custom_bucket_hats = CustomBucketHat.all
      @order_item = current_order.order_items.new
    else
      @brand_id =Brand.find_by(name: params[:brand]).id
      @custom_bucket_hats = CustomBucketHat.where(:brand_id => @brand_id)
    end
  end

  # GET /custom_bucket_hats/1
  # GET /custom_bucket_hats/1.json
  def show
    @order_item = current_order.order_items.new
    @add_texts = AddText.all
    @upload_logos = UploadLogo.all
  end

  # GET /custom_bucket_hats/new
  def new
    @custom_bucket_hat = CustomBucketHat.new
    @brands = Brand.all.map{|b| [b.name,b.id]}
  end

  # GET /custom_bucket_hats/1/edit
  def edit
    @brands = Brand.all.map{|b| [b.name,b.id]}
  end

  # POST /custom_bucket_hats
  # POST /custom_bucket_hats.json
  def create
    @custom_bucket_hat = CustomBucketHat.new(custom_bucket_hat_params)
    @custom_bucket_hat.brand_id = params[:brand_id]

    respond_to do |format|
      if @custom_bucket_hat.save
        format.html { redirect_to @custom_bucket_hat, notice: 'Custom bucket hat was successfully created.' }
        format.json { render :show, status: :created, location: @custom_bucket_hat }
      else
        format.html { render :new }
        format.json { render json: @custom_bucket_hat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /custom_bucket_hats/1
  # PATCH/PUT /custom_bucket_hats/1.json
  def update
    @custom_bucket_hat.brand_id = params[:brand_id]
    respond_to do |format|
      if @custom_bucket_hat.update(custom_bucket_hat_params)
        format.html { redirect_to @custom_bucket_hat, notice: 'Custom bucket hat was successfully updated.' }
        format.json { render :show, status: :ok, location: @custom_bucket_hat }
      else
        format.html { render :edit }
        format.json { render json: @custom_bucket_hat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /custom_bucket_hats/1
  # DELETE /custom_bucket_hats/1.json
  def destroy
    @custom_bucket_hat.destroy
    respond_to do |format|
      format.html { redirect_to custom_bucket_hats_url, notice: 'Custom bucket hat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_custom_bucket_hat
      @custom_bucket_hat = CustomBucketHat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def custom_bucket_hat_params
      params.require(:custom_bucket_hat).permit(:title, :logo, :image, :back_image, :left_image, :right_image, :price, :product_detail, :order_id, :cart_id, :category_id, :quantity, :text)
    end
end

app/helpers/custom_bucket_hats_helper.rb
module CustomBucketHatsHelper
end

app/views/custom_bucket_hats/_form.html.erb
<%= form_with(model: custom_bucket_hat, local: true) do |form| %>
  <% if custom_bucket_hat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(custom_bucket_hat.errors.count, "error") %> prohibited this custom_bucket_hat from being saved:</h2>

      <ul>
      <% custom_bucket_hat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :custom_bucket_hat_title %>
  </div>

  <div class="field">
    <%= form.label :logo %>
    <%= form.file_field :logo, id: :custom_bucket_hat_logo %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :custom_bucket_hat_image %>
  </div>

  <div class="field">
    <%= form.label :back_image %>
    <%= form.file_field :back_image, id: :custom_bucket_hat_back_image %>
  </div>

  <div class="field">
    <%= form.label :left_image %>
    <%= form.file_field :left_image, id: :custom_bucket_hat_left_image %>
  </div>

  <div class="field">
    <%= form.label :right_image %>
    <%= form.file_field :right_image, id: :custom_bucket_hat_right_image %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :custom_bucket_hat_price %>
  </div>

  <div class="field">
    <%= form.label :product_detail %>
    <%= form.text_field :product_detail, id: :custom_bucket_hat_product_detail %>
  </div>
  
  <div class="form-group">
    <div class="row">
      <%= select_tag(:brand_id, options_for_select(@brands), :prompt => "select add brand") %>
    </div>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/custom_bucket_hats/edit.html.erb
<h1>Editing Custom Bucket Hat</h1>

<%= render 'form', custom_bucket_hat: @custom_bucket_hat %>

<%= link_to 'Show', @custom_bucket_hat %> |
<%= link_to 'Back', custom_bucket_hats_path %>

app/views/custom_bucket_hats/index.html.erb
<div class="container-fluid">
<div class="main-section">
	<ul class="hidden-xs sort-list list-inline text-center">
		<li class=""><%= link_to "Snapbacks", custom_snapbacks_path %></li>
		<li class=""><%= link_to "Fitted Hats", custom_fitted_hats_path %> </a></li>
		<li class=""><%= link_to "Dad Hats", custom_strapback_hats_path %></li>
		<li class=""><%= link_to "Camo Hats", custom_camo_hats_path %></li>
		<li class=""><%= link_to "Beanies", custom_beanies_path %></li>
		<li class=""><%= link_to "5 Panel Hats", custom_panel_hats_path %></li>
		<li class=""><%= link_to "Trucker Hats", custom_trucker_hats_path %></li>
		<li class="active"><%= link_to "Bucket Hats", custom_bucket_hats_path %></li>
		<li class=""><%= link_to "Athletic Hats", custom_athletic_hats_path %></li>
		<li class=""><%= link_to "Golf Hats", custom_golf_hats_path %></li>
		<li class=""><%= link_to "Military Hats", custom_military_hats_path %></li>
	</ul>
	<header class="heading text-center">
	<h1>Design your own Custom bucket Hats</h1>
	</header>
<div class="row mb20">
	<ul class="products-list list-unstyled text-center">
		<% @custom_bucket_hats.each do |custom_bucket_hat| %> 
						<li class="col-sm-4">
							<div class="img-holder" itemscope itemtype="http://schema.org/Product" id="product_1">
								<a href="/products/flat-bill-snapback-new-era?taxon_id=7">
									<picture>
										<a alt="Flat bill snapback cap - New Era 9Fifty - New Era NE400 - CapBeast" class="img-responsive" itemprop="url">
										    <a href="/custom_bucket_hats/<%= custom_bucket_hat.id %>"><%= image_tag custom_bucket_hat.image.url, class: "img-responsive", id: "theImage" %>
											</a>
										</a>
									</picture>
								</a>
							</div>
							<ul class="set-color list-inline">
								</li>
									<li>
										<a href="#" class="change_product_image" style="background: linear-gradient(to bottom, #747D7D 0%, #747D7D 100%);"></a>
							
									</li>
								</li>
									<li>
									<a href="#" class="change_product_image" style="background: linear-gradient(to bottom, #15125C 0%, #15125C 100%);"></a>
									<div class="variant_source hide" id="https://uploads.capbeast.com/spree/products/191992/product/IMG_0128.jpg?1475692723"></div>
									</li>
									<li>
									<a href="#" class="change_product_image" style="background: linear-gradient(to bottom, #030303  0%, #030303  50%,  #1F5919  50%,  #1F5919  100%);"></a>
									<div class="variant_source hide" id="https://uploads.capbeast.com/spree/products/261065/product/FLAT_BILL_9FIFTY_SNAPBACK__NEW_ERA_CAMO_-_Front_View.jpg?1485186371"></div>
									</li>
								</li>
									<li>
									<a href="#" class="change_product_image" style="background: linear-gradient(to bottom, #D6C994 0%, #D6C994 100%);"></a>
									<div class="variant_source hide" id="https://uploads.capbeast.com/spree/products/722/product/IMG_0139.jpg?1412110055"></div>
									</li>
									<li>
									<a href="#" class="change_product_image" style="background: linear-gradient(to bottom, #000000  0%, #000000  50%,  #030303 50%,  #030303 100%);"></a>
									<div class="variant_source hide" id="https://uploads.capbeast.com/spree/products/191987/product/IMG_0131.jpg?1475692677"></div>
									</li>
							</ul>
							<strong class="title"><a href="/custom_bucket_hats/<%= custom_bucket_hat.id %>" itemprop="name" title="Flat bill 9Fifty snapback | New Era"><%= custom_bucket_hat.title %></a></strong>
							<strong class="price">$<%= custom_bucket_hat.price %></strong>
						</li>
					<% end %>
</ul>
<div class="row">
<div class="col-sm-2 col-sm-offset-5 text-center">
</div>
</div>
</div>
<div class="row">
<ul class="products-list list-unstyled text-center">
<li class="col-sm-4">
<div class="img-holder sub-categories" itemscope itemtype="http://schema.org/Product" id="category_35">
<a href=/custom-hats/custom-fitted-hats/custom-new-era-fitted-hats>
<picture>
<a href="/custom-hats/custom-fitted-hats/custom-new-era-fitted-hats" itemprop="url"><img alt="New era fitted hats" class="img-responsive" data-src="https://uploads.capbeast.com/spree/taxons/35/exact/new-era-fitted-hats.jpg?1429180862" itemprop="image" src="https://uploads.capbeast.com/spree/taxons/35/exact/new-era-fitted-hats.jpg?1429180862" /></a>
</picture>
</a>
</div>
<div class="title">
<a title="Sample Cap" itemprop="name" href=/custom-hats/custom-fitted-hats/custom-new-era-fitted-hats class="info product-name text-center">Custom New Era Fitted Hats</a>
</div>
</li>
<li class="col-sm-4">
<div class="img-holder sub-categories" itemscope itemtype="http://schema.org/Product" id="category_38">
<a href=/custom-hats/custom-fitted-hats/custom-flexfit-fitted-hats>
<picture>
<a href="/custom-hats/custom-fitted-hats/custom-flexfit-fitted-hats" itemprop="url"><img alt="Flexfit fitted hats" class="img-responsive" data-src="https://uploads.capbeast.com/spree/taxons/38/exact/flexfit-fitted-hats.jpg?1429180863" itemprop="image" src="https://uploads.capbeast.com/spree/taxons/38/exact/flexfit-fitted-hats.jpg?1429180863" /></a>
</picture>
</a>
</div>
<div class="title">
<a title="Sample Cap" itemprop="name" href=/custom-hats/custom-fitted-hats/custom-flexfit-fitted-hats class="info product-name text-center">Custom Flexfit Fitted Hats</a>
</div>
</li>
</ul>
</div>
<div class="row mb20">
<div class="col-sm-12">
<p class=""><p>Let&rsquo;s take it all the way back to the 1920s and talk about the start of the custom fitted. Way before its adjustable brother and sisters hit the scene in the 1940s, the fitted was New Era&rsquo;s first pride and joy. Although it never quite turned out to be the pop culture giant the snapback is; the 59Fifty has still made waves around the world with it&rsquo;s unique take on the original baseball cap. Nicknamed &lsquo;The Brooklyn Style Cap&rsquo;, the fitted is the cap of choice for sports enthusiasts globally.</p>
<p>&ldquo;<em><strong>Where every fitted hat mean a different hood, make it out and they still want you in the hood&rdquo; &ndash;&nbsp;</strong></em><strong>Nipsey Hu$$le</strong></p>
<p>The basic and most obvious difference between the fitted and the other types of custom hats available on the market is the lack of closure mechanic at the back. Because of this, the fitted uniquely lends its self to more fully customizable style of fashion garment. If you&rsquo;re looking to truly design a bespoke custom baseball hat from the peak to the back then this is the piece for you.</p>
<p>&ldquo;<em><strong>Old to the new, no school holds the hat, custom tailor fitted, head stay the same size&rdquo; -&nbsp;</strong></em><strong>MF Doom</strong></p>
<p>Not only does the fitted hats design lend its self to some ridiculously dope style choices, it&rsquo;s also the most comfortable hat on the market by a long shot. If you&rsquo;re looking for a cap with style and practicality, you can&rsquo;t beat a good 59Fifty or FlexiFit that will rest snuggly on your head whatever the size. Due to its unique elasticity material, you won&rsquo;t ever have to worry about adjusting uncomfortable closures. Your head and a custom fitted are truly meant to be together. So why don&rsquo;t you make it official? Pick up a New Era 59Fifty, Yupoong or FlexiFit from CapBeast today. Then christen your brand new dome piece with our ridiculously easy to use online cap customizer. Make that cap yours and no one else&rsquo;s, baby.</p>
</p>
</div>
</div>
<div class="row">
<div class="col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
<ul class="sort-list list-inline text-center" style="margin-top:0px">
<li><a href="/custom-hats/custom-fitted-hats/custom-new-era-fitted-hats"> New Era Fitted Hats </a></li>
<li><a href="/custom-hats/custom-fitted-hats/custom-flexfit-fitted-hats"> Flexfit Fitted Hats </a></li>
</ul>
</div>
</div>
</div> 
</div> 

app/views/custom_bucket_hats/new.html.erb
<h1>New Custom Bucket Hat</h1>

<%= render 'form', custom_bucket_hat: @custom_bucket_hat %>

<%= link_to 'Back', custom_bucket_hats_path %>