config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :brands
    get 'home/index' 
    root 'home#index' 
  devise_for :users
  resources :upload_logos
  resources :add_texts
  resources :custom_military_hats
  resources :custom_golf_hats
  resources :custom_athletic_hats
  resources :custom_bucket_hats
  resources :custom_trucker_hats
  resources :custom_panel_hats
  resources :custom_beanies
  resources :custom_camo_hats
  resources :custom_strapback_hats
  resources :custom_fitted_hats
  resources :custom_snapbacks
  get 'home/custom_snapbacks'
  get 'home/custom_fitted_hats'
  get 'home/custom_dad_hats'
  get 'home/custom_camo_hats'
  get 'home/login_form'
  get 'home/forget_psw'
  get 'home/signup_form'
  get 'home/checkout'
  get 'home/checkout_shipping'
  get 'home/checkout_payment'
  get 'home/contact'
  post 'home/contact_us_mailer'
  resources :shippings
  resources :addresses
  resources :order_statuses
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  resources :orders
	resources :charges
  resources :faqs
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	before_action :authenticate_user!
	def show
    	@order_items = current_order.order_items
    	@orders= Order.all
  	end
  	
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart_row.html.erb
<div class="container-fluid">
    <div class="cart-section">
      <div class="row">
        <div class="col-sm-8 col-md-9">
          <h3>Custom Products</h3>
          <table class="cart-table table">
            <thead>
              <tr>
                <th class="col-photo">ITEM</th>
                <th class="col-name"></th>
                <th class="col-unit-price">UNIT PRICE</th>
                <th class="col-qty">QTY</th>
                <th class="col-fee">DIGITIZATION <br> FEE</th>
                <th class="col-price">Total</th>
                <th class="col-actions"></th>
              </tr>
            </thead>
            <tfoot>
              <tr>
                <td colspan="6">
                  <dl class="summary">
                    <dt>Subtotal</dt>
                      <dd>$140.50</dd>
                    <dt><strong>Order Total</strong></dt>
                      <dd><strong>$140.50</strong></dd>
                  </dl>
                </td>
              </tr>
            </tfoot>
            <tbody>
              <%= form_for order_item, remote: true do |f| %>
              <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency order_item.unit_price %></span></h4>
        <div class="row">
          <div class="col-xs-4">
            <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
            <%= f.hidden_field :custom_snapback_id, value: custom_snapback.id %>
          </div>
          <div class="col-xs-8 text-right">
            <div class="btn-group">
              <%= f.submit "Update Quantity", class: "btn btn-primary" %>
              <%= link_to "Delete", order_item, { data: { confirm: "Are you sure you wish to delete the product '#{order_item.custom_snapback.title}' from your cart?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
            </div>
          </div>
        </div>
        <h4 class="text-right">Total Price: <span style="color: green"><%= number_to_currency order_item.total_price %></span></h4>
      <% end %>
            </tbody>
          </table>
        </div>
        <div class="col-sm-4 col-md-3">
          <div class="widget-block">
            <strong class="title">ORDER SUMMARY</strong>
              <dl class="summary">
                <dt>Subtotal</dt>
                  <dd>$140.50</dd>
                <dt>Shipping total: </dt>
                  <dd><strong>-</strong></dd>
                <dt>Taxes: </dt>
                  <dd><strong>-</strong></dd>
                <dt><strong>Order Total</strong></dt>
                  <dd><strong>$140.50</strong></dd>
              </dl>
                <%= link_to 'CHECKOUT NOW', home_checkout_path, class: "btn btn-danger" %>
            <div class="link">
                <%= link_to'Continue Shopping', home_index_path %>
            </div>
          </div>
          <div id="alert-pop">
            <div class="modal fade" id="cart_delete_warning" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-md">
                <div class="modal-content">
                  <div class="modal-header">
                    <br>
                      <h4 class="text-center">Are you sure you want to remove this item from your cart?</h4>
                  </div>
                  <div class="modal-body">
                    <div class="row">
                      <div class="col-sm-12 text-center">
                        <form accept-charset="UTF-8" action="/orders/CB13881788/remove_line_item" method="post"><div style="display:none"><!-- <input name="utf8" type="hidden" value="&#x2713;" /><input name="_method" type="hidden" value="delete" /><input name="authenticity_token" type="hidden" value="sKq6pXGLqUMwvjqqOnK0DEcF3xU4fDN0M4Y6hJv44e8=" /> --></div>
                        <input id="line_item" name="line_item" type="hidden" />
                        <br>
                        <input class="ok btn btn-danger delete-item-from-cart" name="commit" type="submit" value="OK" />
                        <button class="btn btn-default" data-dismiss="modal" value="Cancel">Cancel</button>
                        <br>
                        <br>
                        </form> 
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="widget-block">
            <strong class="title">APPLY DISCOUNT</strong>
              <!-- <form accept-charset="UTF-8" action="/cart" class="discount-form" id="update-cart" method="post"><div style="display:none"><input name="utf8" type="hidden" value="&#x2713;" /><input name="_method" type="hidden" value="patch" /><input name="authenticity_token" type="hidden" value="sKq6pXGLqUMwvjqqOnK0DEcF3xU4fDN0M4Y6hJv44e8=" /></div>
                <div class="form-group">
                  <input type="text" name="order[coupon_code]" class="form-control" placeholder="code">
                </div>
                <input type="submit" value="Apply Coupon" class="btn btn-default">
              </form>  -->
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @order_items.size == 0 %>
  <p class="text-center">
  <h1>
    There are no items in your shopping cart.Please <%= link_to "go back", root_path %> and add some items to your cart.</h1>
  </p>
<% else %>
  <% @order_items.each do |order_item| %>
    <%= render 'carts/cart_row', custom_snapbacks: order_item.custom_snapback, order_item: order_item, show_total: true %>
  <% end %>
<% end %>

app/views/carts/show.html.erb
<center><h1>My Cart</h1></center>
<div class="shopping-cart">
  <%= render "carts/shopping_cart" %>
</div>