config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :brands
    get 'home/index' 
    root 'home#index' 
  devise_for :users
  resources :upload_logos
  resources :add_texts
  resources :custom_military_hats
  resources :custom_golf_hats
  resources :custom_athletic_hats
  resources :custom_bucket_hats
  resources :custom_trucker_hats
  resources :custom_panel_hats
  resources :custom_beanies
  resources :custom_camo_hats
  resources :custom_strapback_hats
  resources :custom_fitted_hats
  resources :custom_snapbacks
  get 'home/custom_snapbacks'
  get 'home/custom_fitted_hats'
  get 'home/custom_dad_hats'
  get 'home/custom_camo_hats'
  get 'home/login_form'
  get 'home/forget_psw'
  get 'home/signup_form'
  get 'home/checkout'
  get 'home/checkout_shipping'
  get 'home/checkout_payment'
  get 'home/contact'
  post 'home/contact_us_mailer'
  resources :shippings
  resources :addresses
  resources :order_statuses
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  resources :orders
	resources :charges
  resources :faqs
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def new
	end

	def create
	  # Amount in cents
	  @amount = 500

	  customer = Stripe::Customer.create(
	    :email => params[:stripeEmail],
	    :source  => params[:stripeToken]
	  )

	  charge = Stripe::Charge.create(
	    :customer    => customer.id,
	    :amount      => @amount,
	    :description => 'Rails Stripe customer',
	    :currency    => 'usd'
	  )

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to new_charge_path
	end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/_new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto">     
  </script>
<% end %>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>